### ISSUE TITLE
Android build crashes when opening window

### ISSUE THREAD

**Issue by kaiiserni** [appcelerator/hyperloop-examples#48]
The android build crashes in the emulator and on device when opening a window:

```
[ERROR] KrollProxy: (main) [14293,19746] Error creating proxy
[ERROR] KrollProxy: java.lang.NoSuchMethodException: <init> [class org.appcelerator.titanium.TiContext]
[ERROR] KrollProxy: 	at java.lang.Class.getConstructor(Class.java:528)
[ERROR] KrollProxy: 	at java.lang.Class.getConstructor(Class.java:492)
[ERROR] KrollProxy: 	at org.appcelerator.kroll.KrollProxy.createDeprecatedProxy(KrollProxy.java:161)
[ERROR] KrollProxy: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[ERROR] KrollProxy: 	at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[ERROR] KrollProxy: 	at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:918)
[ERROR] KrollProxy: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1141)
[ERROR] KrollProxy: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:357)
[ERROR] KrollProxy: 	at ti.modules.titanium.ui.widget.listview.ListViewProxy.handleMessage(ListViewProxy.java:312)
[ERROR] KrollProxy: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] KrollProxy: 	at android.os.Looper.loop(Looper.java:234)
[ERROR] KrollProxy: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
[ERROR] KrollProxy: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] KrollProxy: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[ERROR] KrollProxy: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[ERROR] D/ACDB-LOADER(  659): ACDB -> send_audio_cal, acdb_id = 4, path =  1
[ERROR] D/ACDB-LOADER(  659): ACDB -> send_asm_topology
[ERROR] D/ACDB-LOADER(  659): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
[ERROR] D/ACDB-LOADER(  659): ACDB -> send_adm_topology
[ERROR] D/ACDB-LOADER(  659): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
[ERROR] D/ACDB-LOADER(  659): ACDB -> send_audtable
[ERROR] D/ACDB-LOADER(  659): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
[ERROR] D/        (  659): Failed to fetch the lookup information of the device 00000004
[ERROR] E/ACDB-LOADER(  659): Error: ACDB audproc returned = -19
[ERROR] D/ACDB-LOADER(  659): ACDB -> AUDIO_SET_AUDPROC_CAL
[ERROR] D/ACDB-LOADER(  659): ACDB -> send_audvoltable
[ERROR] D/ACDB-LOADER(  659): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
[ERROR] D/        (  659): Failed to fetch the lookup information of the device 00000004
[ERROR] E/ACDB-LOADER(  659): Error: ACDB AudProc vol returned = -19
[ERROR] D/ACDB-LOADER(  659): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
[ERROR] D/ACDB-LOADER(  659): ACDB -> send_afe_cal
[ERROR] D/ACDB-LOADER(  659): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
[ERROR] D/        (  659): Failed to fetch the lookup information of the device 00000004
[ERROR] E/ACDB-LOADER(  659): Error: ACDB AFE returned = -19
[ERROR] D/ACDB-LOADER(  659): ACDB -> AUDIO_SET_AFE_CAL
[ERROR] D/ACDB-LOADER(  659): ACDB -> send_hw_delay : acdb_id = 4 path = 1
[ERROR] D/ACDB-LOADER(  659): ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
[ERROR] D/ACDB-LOADER(  659): ACDB -> send_audio_cal, acdb_id = 124, path =  0
[ERROR] D/ACDB-LOADER(  659): ACDB -> send_asm_topology
[ERROR] D/ACDB-LOADER(  659): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
[ERROR] D/ACDB-LOADER(  659): ACDB -> send_adm_topology
[ERROR] D/ACDB-LOADER(  659): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
[ERROR] D/ACDB-LOADER(  659): ACDB -> send_audtable
[ERROR] D/ACDB-LOADER(  659): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
[ERROR] D/ACDB-LOADER(  659): ACDB -> AUDIO_SET_AUDPROC_CAL
[ERROR] D/ACDB-LOADER(  659): ACDB -> send_audvoltable
[ERROR] D/ACDB-LOADER(  659): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
[ERROR] D/ACDB-LOADER(  659): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
[ERROR] D/ACDB-LOADER(  659): ACDB -> send_afe_cal
[ERROR] D/ACDB-LOADER(  659): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
[ERROR] D/ACDB-LOADER(  659): ACDB -> AUDIO_SET_AFE_CAL
[ERROR] D/ACDB-LOADER(  659): ACDB -> send_hw_delay : acdb_id = 124 path = 0
[ERROR] D/ACDB-LOADER(  659): ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
```

**Comment by kaiiserni** [comment]
The issue was related to SDK 5.5.0 not being compatible with Hyperloop 1.2.6 somehow although I was under the impression that I upgraded everything. Closing ticket ;-)
